# Generated by Django 5.1.6 on 2025-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_document_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gemini_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gemini_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='resume_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
